// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrrQTOPMyMSBV5wxHFh7qnvhdXJWydluw',
    appId: '1:961926818771:android:bff83cc3a93b920f135d26',
    messagingSenderId: '961926818771',
    projectId: 'sampleweatherapp-14130',
    storageBucket: 'sampleweatherapp-14130.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH0pqLW2EowDOPotP36es6JmhDa5aMNzE',
    appId: '1:961926818771:ios:e6ee7f69d93c914f135d26',
    messagingSenderId: '961926818771',
    projectId: 'sampleweatherapp-14130',
    storageBucket: 'sampleweatherapp-14130.firebasestorage.app',
    androidClientId: '961926818771-3n0bridr5t8asn159ifbk29057kb2at9.apps.googleusercontent.com',
    iosClientId: '961926818771-cvb3em1u6ia5kkeitlfknmd0bnpmmob7.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

}